# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
    adapter: mysql2 
    encoding: utf8 
    database: pspwebapp
    username: pspdb
    password: 'pspwebapp' 
    pool: 5 
    host: 77.68.63.19
    reconnect: false
